name: toastr
version: 0.2.0
description: Port of toastr to Dart.
environment:
  sdk: '>=2.0.0 <3.0.0'
author: Kevin Visscher <kevin@clickseeker.nl>
homepage: https://github.com/kvisscher/toastr
dependencies:
  test: ^1.14.5
